export interface SupplierDTO {
  supplier_id?: number;         // Optional because it's generated by backend
  store_id: number;
  address_id: number;
  name: string;
  contact_person_name: string;
  contact_person_email: string;
  contact_person_phone: string;
  
  // Optional/Metadata fields (Backend often sends these)
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}